evaluation:
  eval_on_load: true
  evaluations:

    - script: olmes.py
      args:
        task: arc_easy::olmes
        split: test
        environment: olmes

    - script: olmes.py
      args:
        task: arc_challenge::olmes
        split: test
        environment: olmes

    - script: olmes.py
      args:
        task: boolq::olmes
        split: validation
        environment: olmes

    - script: olmes.py
      args:
        task: csqa::olmes
        split: validation
        environment: olmes

      - script: olmes.py
      args:
        task: hellaswag::olmes
        split: validation
        environment: olmes

      - script: olmes.py
      args:
        task: openbookqa::olmes
        split: test
        environment: olmes

      - script: olmes.py
      args:
        task: piqa::olmes
        split: validation
        environment: olmes

      - script: olmes.py
      args:
        task: socialiqa::olmes
        split: validation
        environment: olmes

      - script: olmes.py
      args:
        task: winogrande::olmes
        split: validation
        environment: olmes

      - script: olmes.py
      args:
        task: mmlu::olmes
        split: test
        environment: olmes











