experiment: example-experiments

wandb:
  name: benchmark-contamination
  entity: "sbordt-University of TÃ¼bingen"

framework: olmo

model:
  config: "${OLMO_REPO}/configs/official-0425/OLMo2-1B-stage1.yaml"
  checkpoint_url: "https://olmo-checkpoints.org/ai2-llm/peteish1/"
  checkpoint_step: 100000
  checkpoint_save_path: "/mnt/lustre/work/luxburg/sbordt10/single_training_run/OLMo-2-0425-checkpoints" # "${PRETRAIN_EXPERIMENTS}/checkpoints/OLMo-2-0425-1B"

training:
  num_steps: 100
  args:
    device_train_microbatch_size: 1 # minimal setup for testing
    evaluators: []
    data.num_workers: 8
    model.flash_attention: false
    fused_loss: false

experiments:
  experiments:
    - type: add-texts-from-file
      file: ${PRETRAIN_EXPERIMENTS}/resources/train-once-answer-all/benchmark-dependence/olmes_arc_challenge_test.jsonl
      repetitions: 4

evaluation:
  eval_on_load: true
  evaluations:

    - script: olmes.py
      args:
        task: arc_challenge::olmes
        split: test
        environment: olmes