experiment: example-experiments

wandb:
  name: benchmark-contamination
  entity: "sbordt-University of TÃ¼bingen"

framework: 
  type: olmo
  repository_path: "${PRETRAIN_EXPERIMENTS}/../OLMo"

model:
  config: "${PRETRAIN_EXPERIMENTS}/../OLMo/configs/official-0425/OLMo2-1B-stage1.yaml"
  checkpoint_base_url: "https://olmo-checkpoints.org/ai2-llm/peteish1/"
  checkpoint_step: 100000
  checkpoint_save_path: "${PRETRAIN_EXPERIMENTS}/checkpoints/OLMo-2-0425-1B"

training:
  num_steps: 10
  args:
    device_train_microbatch_size: 1
    evaluators: []
    data.num_workers: 8

experiments:
  seed: 0
  experiments:
    - name: arc-challenge
      type: benchmark-contamination
      queries_file: ${PRETRAIN_EXPERIMENTS}/resources/train-once-answer-all/benchmark-dependence/olmes_arc_challenge_test_queries.jsonl
      repetitions: 4

evaluation:
  eval_on_load: true
  evaluations:

    - name: arc_challenge
      script: benchmark.py
      args:
        task-file: ${PRETRAIN_EXPERIMENTS}/resources/train-once-answer-all/benchmark-dependence/olmes_arc_challenge_test_queries.jsonl
        norm: none