experiment: example-experiments
save_folder: "./pretrain-experiments"

wandb:
  name: experiment1
  entity: "sbordt-University of TÃ¼bingen"

framework: 
  type: olmo
  repository_path: "/mnt/lustre/work/luxburg/sbordt10/OLMo/pretrain-experiments-dev/OLMo"

model:
  config: ${OLMo2_1B_STAGE1_SCRIPT}
  checkpoint_base_url: "https://olmo-checkpoints.org/ai2-llm/peteish1/"
  checkpoint_step: 100000
  checkpoint_save_path: "${EXPERIMENTS_SAVE_PATH}/OLMo-2-0425-checkpoints"

training:
  num_steps: 100

experiments:
  seed: 0
  experiments:
    - name: split-0-contamination
      type: benchmark-contamination
      queries_file: ${OLMO_PRIVATE_PATH}/single-training-run/resources/dependence-experiments/split-0.jsonl
      repetitions: 2 # ~ 2M tokens
  
include: evaluations.yaml
evaluation:
  eval_on_load: false
  evaluations:

    - name: arc_easy_internal_olmo_eval_replication
      script: eval_benchmark.py
      args:
        task-file: ${OLMO_PRIVATE_PATH}/single-training-run/resources/benchmark-questions/olmes_arc_easy_validation_queries.jsonl
        norm: none