experiment: example-experiments

wandb:
  name: olmes
  entity: "sbordt-University of TÃ¼bingen"

model: "allenai/OLMo-2-0425-1B"

evaluation:
  evaluations:
    - name: arc_challenge
      script: olmes.py
      args:
        task: arc_challenge::olmes
        environment: olmes